[project]
name = "leanllm"
version = "0.1.0"
description = "leanllm"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.9.1",
    "transformers>=4.57.3",
]

[project.scripts]
leanllm = "leanllm.cli:main"
